server:
  forward-headers-strategy: framework
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./index
    username: sa
    password: